apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mahesh
  name: mahesh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mahesh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mahesh
    spec:
      containers:
      - image: maheshpenna96/votingapp:vote
        name: nginx
      imagePullSecrets:
      - name: docker-pwd
