apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
  namespace: my-namespace
spec:
  limits:
  - default:
      memory: "512Mi"       # Default memory limit if not specified by the container
      cpu: "500m"           # Default CPU limit if not specified by the container
    defaultRequest:
      memory: "256Mi"       # Default memory request if not specified by the container
      cpu: "250m"           # Default CPU request if not specified by the container
    type: Container
  - max:
      memory: "1Gi"         # Maximum memory limit allowed for a container
      cpu: "1"              # Maximum CPU limit allowed for a container
    min:
      memory: "128Mi"       # Minimum memory limit required for a container
      cpu: "100m"           # Minimum CPU limit required for a container
    type: Container
