apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: my-namespace
spec:
  hard:
    requests.cpu: "4"            # Total CPU requested across all pods (4 CPUs)
    requests.memory: "8Gi"       # Total memory requested across all pods (8Gi)
    limits.cpu: "8"              # Max CPU limit across all pods (8 CPUs)
    limits.memory: "16Gi"        # Max memory limit across all pods (16Gi)
    pods: "10"                   # Max number of pods in the namespace
    services: "5"                # Max number of services in the namespace
    persistentvolumeclaims: "3"  # Max number of PVCs in the namespace
